import { createClient } from "@supabase/supabase-js";
import { getCasoBySlug as getStaticCasoBySlug, getCasosPublicados as getStaticCasosPublicados, type Caso, type FotoCaso } from "@/data/casos";

type PublicClinicalCaseRow = {
  id: string;
  slug: string;
  title: string;
  subtitle: string | null;
  description: string;
  seo_title: string | null;
  seo_description: string | null;
  categories: string[] | null;
  duration: string | null;
  pieces: string | null;
  technique: string | null;
  copy: string;
  copy_social: string | null;
  published_at: string | null;
  status: string;
  translations: Record<string, {
    title?: string;
    subtitle?: string;
    description?: string;
    seoTitle?: string;
    seoDescription?: string;
    categories?: string[];
    duration?: string;
    pieces?: string;
    technique?: string;
    copy?: string;
  }> | null;
};

type PublicClinicalCaseAssetRow = {
  case_id: string;
  public_url: string;
  alt: string;
  caption: string | null;
  role: string;
  sort_order: number;
  translations: Record<string, { alt?: string; caption?: string }> | null;
};

// Versiones de importación que no deben competir con el caso editorial definitivo.
// Se conservan con redirect permanente, pero se excluyen de listados y sitemap.
const LEGACY_CASE_SLUGS = new Set([
  "gingivectomia-laser-10-procedimiento-recorte-gingival",
  "gingivectomia-laser-09-antes-despues-comparativa-2",
]);

/**
 * Control de calidad genérico para casos del bridge de Supabase.
 *
 * `LEGACY_CASE_SLUGS` bloquea los casos basura ya conocidos; este gate atrapa
 * los FUTUROS: el pipeline de subida deriva el título del nombre del archivo
 * (p. ej. "gingivectomia laser 10 procedimiento recorte gingival"), y un título
 * así no debe llegar nunca a la galería pública. Si el título no parece escrito
 * por una persona, el caso se oculta hasta que se le dé un título real.
 */
function looksAutogeneratedTitle(title: string | null | undefined): boolean {
  const t = (title || "").trim();
  if (!t) return true;
  const first = t[0];
  // Un título real empieza con mayúscula ("Gingivectomía…"), no con minúscula.
  if (first && first.toLocaleLowerCase("es") === first && first.toLocaleUpperCase("es") !== first) return true;
  // Un título sin ninguna mayúscula es, casi con certeza, un nombre de archivo.
  if (!/[A-ZÁÉÍÓÚÜÑ]/.test(t)) return true;
  // Parece un slug (sin espacios, con guiones) en vez de una frase.
  if (!/\s/.test(t) && t.includes("-")) return true;
  return false;
}

function getSupabasePublic() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anon) return null;

  return createClient(url, anon, { auth: { persistSession: false } });
}

function mapAssetToFoto(asset: PublicClinicalCaseAssetRow, lang: "es" | "en"): FotoCaso {
  const localized = lang === "en" ? asset.translations?.en : undefined;
  return {
    src: asset.public_url,
    alt: localized?.alt || asset.alt,
    caption: localized?.caption || asset.caption || undefined,
  };
}

function mapDynamicCase(
  row: PublicClinicalCaseRow,
  assets: PublicClinicalCaseAssetRow[],
  lang: "es" | "en",
): Caso | null {
  const localized = lang === "en" ? row.translations?.en : undefined;
  const fotos = assets
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((asset) => mapAssetToFoto(asset, lang));

  const fotoPortada = fotos[0];
  if (!fotoPortada) return null;

  return {
    slug: row.slug,
    titulo: localized?.title || row.title,
    subtitulo: localized?.subtitle || localized?.description || row.subtitle || row.description,
    descripcion: localized?.description || row.description,
    seoTitle: localized?.seoTitle || row.seo_title || undefined,
    seoDescription: localized?.seoDescription || row.seo_description || undefined,
    categorias: localized?.categories || row.categories || (lang === "en" ? ["Clinical case"] : ["Caso clínico"]),
    duracion: localized?.duration || row.duration || (lang === "en" ? "Clinical case" : "Caso clínico"),
    piezas: localized?.pieces || row.pieces || undefined,
    tecnica: localized?.technique || row.technique || undefined,
    fotoPortada,
    fotos,
    copy: localized?.copy || localized?.description || row.copy,
    copyRedes: row.copy_social || undefined,
    publicado: row.status === "published",
  };
}

export async function getDynamicCasosPublicados(lang: "es" | "en" = "es"): Promise<Caso[]> {
  const supabase = getSupabasePublic();
  if (!supabase) return [];

  const { data: caseRows, error: caseError } = await supabase
    .from("public_clinical_cases")
    .select("id, slug, title, subtitle, description, seo_title, seo_description, categories, duration, pieces, technique, copy, copy_social, published_at, status, translations")
    .eq("status", "published")
    .order("published_at", { ascending: false });

  if (caseError || !caseRows?.length) return [];

  const caseIds = caseRows.map((row) => row.id);
  const { data: assetRows, error: assetError } = await supabase
    .from("public_clinical_case_assets")
    .select("case_id, public_url, alt, caption, role, sort_order, translations")
    .in("case_id", caseIds)
    .order("sort_order", { ascending: true });

  if (assetError) return [];

  const assetsByCase = new Map<string, PublicClinicalCaseAssetRow[]>();
  for (const asset of (assetRows || []) as PublicClinicalCaseAssetRow[]) {
    const bucket = assetsByCase.get(asset.case_id) || [];
    bucket.push(asset);
    assetsByCase.set(asset.case_id, bucket);
  }

  return (caseRows as PublicClinicalCaseRow[])
    .filter((row) => {
      if (looksAutogeneratedTitle(row.title)) {
        console.warn(`[public-cases] Caso oculto por título auto-generado (sin curar): "${row.title}" (slug: ${row.slug}).`);
        return false;
      }
      return true;
    })
    .map((row) => mapDynamicCase(row, assetsByCase.get(row.id) || [], lang))
    .filter((value): value is Caso => Boolean(value));
}

export async function getCasosPublicadosMerged(lang: "es" | "en" = "es"): Promise<Caso[]> {
  const staticCases = getStaticCasosPublicados();
  const dynamicCases = await getDynamicCasosPublicados(lang);

  // El caso curado (estático) es autoritativo: se aplica ÚLTIMO para que gane
  // sobre su equivalente del bridge con el mismo slug (evita, p. ej., que una
  // fila con imágenes rotas pise al caso curado con fotos que sí cargan).
  const merged = new Map<string, Caso>();
  for (const caso of dynamicCases) merged.set(caso.slug, caso);
  for (const caso of staticCases) merged.set(caso.slug, caso);

  return Array.from(merged.values()).filter((caso) => !LEGACY_CASE_SLUGS.has(caso.slug));
}

export async function getCasoBySlugMerged(slug: string, lang: "es" | "en" = "es"): Promise<Caso | undefined> {
  if (LEGACY_CASE_SLUGS.has(slug)) return undefined;
  // Curado (estático) primero — es la fuente autoritativa.
  const staticCase = getStaticCasoBySlug(slug);
  if (staticCase) return staticCase;
  const dynamicCases = await getDynamicCasosPublicados(lang);
  return dynamicCases.find((caso) => caso.slug === slug);
}
